server:
  port: 8080

mybatis:
  config-location: classpath:META-INF/mybatis-config.xml
  mapper-locations: classpath:META-INF/mappers/*.xml
  type-aliases-package: me.mingshan.tx.dao

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tx_demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: admin
    hikari:
      # 是否自动提交
      auto-commit: true
      # 如果在没有连接可用的情况下超过此时间，则将抛出SQLException
      connection-timeout: 30000
      # 控制允许连接在池中空闲的最长时间
      idle-timeout: 600000
      # 控制池中连接的最长生命周期。使用中的连接永远不会退役，只有当它关闭时才会被删除
      max-lifetime: 1800000
      # 如果您的驱动程序支持JDBC4，强烈建议不要设置此属性
      # connection-test-query:
      # 控制HikariCP尝试在池中维护的最小空闲连接数。建议不要设置此值，而是允许HikariCP充当固定大小的连接池。 默认值：与maximumPoolSize相同
      # minimum-idle:
      # 此属性控制允许池到达的最大大小，包括空闲和正在使用的连接。
      maximum-pool-size: 100
      # 最小空闲连接数量
      minimum-idle: 5
  redis:
    database: 6  #Redis索引0~15，默认为0
    host: 127.0.0.1
    port: 6379
    password:  #密码（默认为空）
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
#    redisson:
#      config: classpath:redisson.yaml

##redis集群版
#redis:
#  timeout: 6000ms
#  database: 0
#  cluster:
#    nodes:
#      - 192.168.40.156:7001
#      - 192.168.40.156:7002
#      - 192.168.40.157:7003
#      - 192.168.40.157:7004
#      - 192.168.40.158:7005
#      - 192.168.40.158:7006
#    max-redirects: 3 # 获取失败 最大重定向次数
#  lettuce:
#    pool:
#      max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
#      max-idle: 10 # 连接池中的最大空闲连接
#      min-idle: 5 # 连接池中的最小空闲连接
#      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

logging:
  level:
    me.mingshan.tx.dao: DEBUG

